genera; more hardcoded paths elimination

diff --git a/test/test-functions b/test/test-functions
--- a/test/test-functions
+++ b/test/test-functions
@@ -8,8 +8,8 @@ KERNEL_VER=${KERNEL_VER-$(uname -r)}
 KERNEL_MODS="/lib/modules/$KERNEL_VER/"
 
 if ! ROOTLIBDIR=$(pkg-config --variable=systemdutildir systemd); then
-    echo "WARNING! Cannot determine rootlibdir from pkg-config, assuming /usr/lib/systemd" >&2
-    ROOTLIBDIR=/usr/lib/systemd
+    echo "WARNING! Cannot determine rootlibdir from pkg-config, assuming /usr/local/lib/InitWare" >&2
+    ROOTLIBDIR=/usr/local/lib/InitWare
 fi
 
 BASICTOOLS="test sh bash setsid loadkeys setfont login sulogin gzip sleep echo mount umount cryptsetup date dmsetup modprobe chmod chown ln sed cmp tee"
@@ -315,15 +315,15 @@ install_terminfo() {
 }
 
 setup_testsuite() {
-    cp $TEST_BASE_DIR/testsuite.target $initdir/etc/systemd/system/
-    sed "s#@SYSTEMCTL@#$(type -P systemctl)#g" $TEST_BASE_DIR/end.service.in > $initdir/etc/systemd/system/end.service
+    cp $TEST_BASE_DIR/testsuite.target $initdir/usr/local/etc/InitWare/system/
+    sed "s#@SYSTEMCTL@#$(type -P systemctl)#g" $TEST_BASE_DIR/end.service.in > $initdir/usr/local/etc/InitWare/system/end.service
 
-    mkdir -p $initdir/etc/systemd/system/testsuite.target.wants
-    ln -fs $TEST_BASE_DIR/testsuite.service $initdir/etc/systemd/system/testsuite.target.wants/testsuite.service
-    ln -fs $TEST_BASE_DIR/end.service $initdir/etc/systemd/system/testsuite.target.wants/end.service
+    mkdir -p $initdir/usr/local/etc/InitWare/system/testsuite.target.wants
+    ln -fs $TEST_BASE_DIR/testsuite.service $initdir/usr/local/etc/InitWare/system/testsuite.target.wants/testsuite.service
+    ln -fs $TEST_BASE_DIR/end.service $initdir/usr/local/etc/InitWare/system/testsuite.target.wants/end.service
 
     # make the testsuite the default target
-    ln -fs testsuite.target $initdir/etc/systemd/system/default.target
+    ln -fs testsuite.target $initdir/usr/local/etc/InitWare/system/default.target
 }
 
 setup_nspawn_root() {
@@ -336,7 +336,7 @@ setup_nspawn_root() {
 
 setup_basic_dirs() {
     mkdir -p $initdir/run
-    mkdir -p $initdir/etc/systemd/system
+    mkdir -p $initdir/usr/local/etc/InitWare/system
     mkdir -p $initdir/var/log/journal
 
     for d in usr/bin usr/sbin bin etc lib "$libdir" sbin tmp usr var var/log dev proc sys sysroot root run run/lock run/initramfs; do
